import Head from "next/head";
import Landing from "../components/LandingSquare";
import { useRouter } from "next/router";
import { useQuery } from "../convex/_generated/react";

import Image from "next/image";

import React, { useState, useEffect } from "react";

import { Select, Button, Box, Grid, GridItem, Heading } from "@chakra-ui/react";

export default function selectUser() {
  const router = useRouter();
  const users = useQuery("getUsers");

  console.log(JSON.stringify(users));

  // const [users, setUsers] = useState({});

  // useEffect(() => {
  //   const getUsers = async () => {
  //     let data = await useQuery("getUsers");
  //     data = JSON.stringify(data);
  //     setUsers(data);
  //     console.log(data);
  //   }

  //   getUsers();
  // }, []);

  const handleStartSession = (e) => {
    e.preventDefault();

    const select = document.getElementById("select");
    const userId = select.value;

    router.push(`./${userId}`);
  };

  return (
    <>
      <Head>
        <title>Denteel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box
        h="100%"
        w="100%"
        display="flex"
        justifyContent="center"
        alignItems="center"
        flexDir="column"
        bg="blue.50"
      >
        <Box
          bg="blue.50"
          w="100%"
          h="200px"
          color="white"
          display="flex"
          justifyContent="center"
          alignItems="center"
          flexDir="column"
        >
          <Grid
            templateColumns="40% 60%"
            templateRows="50% 50%"
            alignItems="center"
            height="200px"
            width="90%"
            columnGap={8}
          >
            <GridItem w="100%" display="flex" justifyContent="end">
              <Image
                src="/images/teeth_svgrepo.com.svg" // Route of the image file
                height={100} // Desired size with correct aspect ratio
                width={100} // Desired size with correct aspect ratio
                alt="logo"
              />
            </GridItem>
            <GridItem w="100%">
              <Heading as="h1" fontSize="50px">
                Denteels
              </Heading>
            </GridItem>
            <GridItem w="100%" colStart={1} colEnd={-1}>
              <Heading as="h1" fontSize="22px" pl="8px" pr="8px">
                A monitor for your patient's oral comfort, to ensure your dental
                practice puts them first.
              </Heading>
            </GridItem>
          </Grid>
        </Box>
        <Box
          h="calc(100vh - 200px)"
          w="90%"
          bg="bblue.50"
          pb="50px"
          display="flex"
          justifyContent="center"
          alignItems="center"
          flexDir="column"
          rowGap="70px"
        >
          <Heading as="h1" fontSize="36px" pl="8px" pr="8px">
            Welcome, Dr. Lanyon
          </Heading>
          <Select id="select" placeholder="Select user" bg="white" w="90%">
            {users &&
              users.map((user) => {
                return (
                  <option value={user._id.toString()} key={user._id.toString()}>
                    {user.name}
                  </option>
                );
              })}
          </Select>
          <Button bg="blue.50" onClick={handleStartSession}>
            Start Session
          </Button>
        </Box>
      </Box>

      {/* <Landing router={router} /> */}
    </>
  );
}
