import Head from "next/head";
import Landing from "../components/LandingSquare";
import { useRouter } from "next/router";
import { useQuery } from "../convex/_generated/react";

import React, { useState, useEffect } from "react";

import { Select, Button } from "@chakra-ui/react";

export default function Home() {
  const router = useRouter();
  const users = useQuery("getUsers");

  console.log(JSON.stringify(users));

  // const [users, setUsers] = useState({});

  // useEffect(() => {
  //   const getUsers = async () => {
  //     let data = await useQuery("getUsers");
  //     data = JSON.stringify(data);
  //     setUsers(data);
  //     console.log(data);
  //   }

  //   getUsers();
  // }, []);

  const handleStartSession = (e) => {
    e.preventDefault();

    const select = document.getElementById("select");
    const userId = select.value; 

    router.push(`./${userId}`);
  };

  return (
    <>
      <Head>
        <title>Denteel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Select id="select" placeholder="Select user">
        {users &&
          users.map((user) => {
            return (
              <option value={user._id.toString()} key={user._id.toString()}>
                {user.name}
              </option>
            );
          })}
      </Select>
      <Button onClick={handleStartSession}>Start Session</Button>

      <Landing router={router} />
    </>
  );
}
